name: alarm

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: 45
          body: |
            Don't forget to merge.
