name: Build with XMake

on:
  push:
    branches: [ "main", "dev", "dev-huancheng" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up XMake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        location: C:\tmp_msys2
        install: >-
          git
          base-devel
          mingw-w64-x86_64-toolchain
    - name: Configure PATH
      run : |
        Add-Content $env:GITHUB_PATH "C:\tmp_msys2\msys64\mingw64\bin"
        Add-Content $env:GITHUB_PATH "C:\tmp_msys2\msys64\usr\bin"
    - name: Configure XMake
      run: xmake f -p mingw --mingw=C:/tmp_msys2/msys64/mingw64 -c --ldflags="-lws2_32 -lwsock32" -y
    - name: Build
      run: xmake
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: xmake-artifact
        path: |
          build\mingw\x86_64\release\*.exe
